### ISSUE TITLE
assertNoPreviousOutput check ?

### ISSUE THREAD

**Issue by hunteryun** [zendframework/zend-httphandlerrrunner#15]
Hi, in my framework, ofter need output someting with ob content, like a image captcha, then I get this error

`
Uncaught Zend\HttpHandlerRunner\Exception\EmitterException: Output has been emitted previously; cannot emit response 

`

so I 'm curious, why do I have to perform a $this->assertNoPreviousOutput(); check?

**Comment by weierophinney** [comment]
Because the assumption with the library is that it alone is responsible for emitting content back to the client.

The reason for that is to ensure that both the HTTP status code and all HTTP headers can be emitted. If any content has been emitted, then the library can no longer do so, and it cannot return a full response.

There are other ways to emit content such as image captchas:

- You can use output buffering to emit and then capture the content to push into a response.
- You can stream the information using a custom PSR-7 StreamInterface implementation.
